language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "anyulled-github"
    token: $SONAR_TOKEN
    
script:
- mvn cobertura:cobertura
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
after_success:
- mvn jacoco:report coveralls:report
- bash <(curl -s https://codecov.io/bash)
